- name: FTP Deploy
  # You may pin to the exact commit or the version.
  # uses: SamKirkland/FTP-Deploy-Action@8a24039354ee91000cb948cb4a1dbdf1a1b94a3c
  uses: SamKirkland/FTP-Deploy-Action@v4.3.4
  with:
    # ftp server
    server: 148.66.137.19
    # ftp username
    username: worldsrank@meetabal.com
    # ftp password
    password: Aqua@1987
    # Server port to connect to (read your web hosts docs)
    port: 21
    # protocol to deploy with - ftp, ftps, or ftps-legacy
    protocol: # optional
    # Folder to upload from, must end with trailing slash /
    local-dir: # optional
    # Path to upload to on the server. Must end with trailing slash /
    server-dir: public_html/worldsrank/codehome/
